# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import llm_service_pb2 as llm__service__pb2

GRPC_GENERATED_VERSION = '1.72.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in llm_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LLMServiceStub(object):
    """LLM Service for text generation
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateText = channel.unary_unary(
                '/llm_service.LLMService/GenerateText',
                request_serializer=llm__service__pb2.GenerateRequest.SerializeToString,
                response_deserializer=llm__service__pb2.GenerateResponse.FromString,
                _registered_method=True)
        self.StreamGenerateText = channel.unary_stream(
                '/llm_service.LLMService/StreamGenerateText',
                request_serializer=llm__service__pb2.GenerateRequest.SerializeToString,
                response_deserializer=llm__service__pb2.StreamGenerateResponse.FromString,
                _registered_method=True)


class LLMServiceServicer(object):
    """LLM Service for text generation
    """

    def GenerateText(self, request, context):
        """Unary RPC for standard text generation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamGenerateText(self, request, context):
        """Server-side streaming RPC for token-by-token generation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LLMServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateText': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateText,
                    request_deserializer=llm__service__pb2.GenerateRequest.FromString,
                    response_serializer=llm__service__pb2.GenerateResponse.SerializeToString,
            ),
            'StreamGenerateText': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamGenerateText,
                    request_deserializer=llm__service__pb2.GenerateRequest.FromString,
                    response_serializer=llm__service__pb2.StreamGenerateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'llm_service.LLMService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('llm_service.LLMService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LLMService(object):
    """LLM Service for text generation
    """

    @staticmethod
    def GenerateText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llm_service.LLMService/GenerateText',
            llm__service__pb2.GenerateRequest.SerializeToString,
            llm__service__pb2.GenerateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamGenerateText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/llm_service.LLMService/StreamGenerateText',
            llm__service__pb2.GenerateRequest.SerializeToString,
            llm__service__pb2.StreamGenerateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
