# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llm_service.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'llm_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11llm_service.proto\x12\x0bllm_service\"`\n\x0fGenerateRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x10\n\x08model_id\x18\x02 \x01(\t\x12\x13\n\x0btemperature\x18\x03 \x01(\x02\x12\x16\n\x0emax_new_tokens\x18\x04 \x01(\x05\"*\n\x10GenerateResponse\x12\x16\n\x0egenerated_text\x18\x01 \x01(\t\"<\n\x16StreamGenerateResponse\x12\x14\n\x0cpartial_text\x18\x01 \x01(\t\x12\x0c\n\x04\x64one\x18\x02 \x01(\x08\x32\xb4\x01\n\nLLMService\x12K\n\x0cGenerateText\x12\x1c.llm_service.GenerateRequest\x1a\x1d.llm_service.GenerateResponse\x12Y\n\x12StreamGenerateText\x12\x1c.llm_service.GenerateRequest\x1a#.llm_service.StreamGenerateResponse0\x01\x42\x03Z\x01.b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llm_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\001.'
  _globals['_GENERATEREQUEST']._serialized_start=34
  _globals['_GENERATEREQUEST']._serialized_end=130
  _globals['_GENERATERESPONSE']._serialized_start=132
  _globals['_GENERATERESPONSE']._serialized_end=174
  _globals['_STREAMGENERATERESPONSE']._serialized_start=176
  _globals['_STREAMGENERATERESPONSE']._serialized_end=236
  _globals['_LLMSERVICE']._serialized_start=239
  _globals['_LLMSERVICE']._serialized_end=419
# @@protoc_insertion_point(module_scope)
