// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: llm_service.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	ModelId       string                 `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"` // prefix routing: "gemma:", "qwen:", "gemini:"
	Temperature   float32                `protobuf:"fixed32,3,opt,name=temperature,proto3" json:"temperature,omitempty"`
	MaxNewTokens  int32                  `protobuf:"varint,4,opt,name=max_new_tokens,json=maxNewTokens,proto3" json:"max_new_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateRequest) Reset() {
	*x = GenerateRequest{}
	mi := &file_llm_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRequest) ProtoMessage() {}

func (x *GenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llm_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRequest.ProtoReflect.Descriptor instead.
func (*GenerateRequest) Descriptor() ([]byte, []int) {
	return file_llm_service_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *GenerateRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *GenerateRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *GenerateRequest) GetMaxNewTokens() int32 {
	if x != nil {
		return x.MaxNewTokens
	}
	return 0
}

type GenerateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GeneratedText string                 `protobuf:"bytes,1,opt,name=generated_text,json=generatedText,proto3" json:"generated_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateResponse) Reset() {
	*x = GenerateResponse{}
	mi := &file_llm_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateResponse) ProtoMessage() {}

func (x *GenerateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llm_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateResponse.ProtoReflect.Descriptor instead.
func (*GenerateResponse) Descriptor() ([]byte, []int) {
	return file_llm_service_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateResponse) GetGeneratedText() string {
	if x != nil {
		return x.GeneratedText
	}
	return ""
}

type StreamGenerateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartialText   string                 `protobuf:"bytes,1,opt,name=partial_text,json=partialText,proto3" json:"partial_text,omitempty"`
	Done          bool                   `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamGenerateResponse) Reset() {
	*x = StreamGenerateResponse{}
	mi := &file_llm_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamGenerateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamGenerateResponse) ProtoMessage() {}

func (x *StreamGenerateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llm_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamGenerateResponse.ProtoReflect.Descriptor instead.
func (*StreamGenerateResponse) Descriptor() ([]byte, []int) {
	return file_llm_service_proto_rawDescGZIP(), []int{2}
}

func (x *StreamGenerateResponse) GetPartialText() string {
	if x != nil {
		return x.PartialText
	}
	return ""
}

func (x *StreamGenerateResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type EvaluateRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Prompt          string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	ReferenceAnswer string                 `protobuf:"bytes,2,opt,name=reference_answer,json=referenceAnswer,proto3" json:"reference_answer,omitempty"` // ground-truth for BLEU/ROUGE
	ModelIds        []string               `protobuf:"bytes,3,rep,name=model_ids,json=modelIds,proto3" json:"model_ids,omitempty"`                      // list of model_id values to compare
	Temperature     float32                `protobuf:"fixed32,4,opt,name=temperature,proto3" json:"temperature,omitempty"`
	MaxNewTokens    int32                  `protobuf:"varint,5,opt,name=max_new_tokens,json=maxNewTokens,proto3" json:"max_new_tokens,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EvaluateRequest) Reset() {
	*x = EvaluateRequest{}
	mi := &file_llm_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateRequest) ProtoMessage() {}

func (x *EvaluateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llm_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateRequest.ProtoReflect.Descriptor instead.
func (*EvaluateRequest) Descriptor() ([]byte, []int) {
	return file_llm_service_proto_rawDescGZIP(), []int{3}
}

func (x *EvaluateRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *EvaluateRequest) GetReferenceAnswer() string {
	if x != nil {
		return x.ReferenceAnswer
	}
	return ""
}

func (x *EvaluateRequest) GetModelIds() []string {
	if x != nil {
		return x.ModelIds
	}
	return nil
}

func (x *EvaluateRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *EvaluateRequest) GetMaxNewTokens() int32 {
	if x != nil {
		return x.MaxNewTokens
	}
	return 0
}

// Per-model metrics returned by both Evaluate and Benchmark RPCs
type ModelMetrics struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ModelId          string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	GeneratedText    string                 `protobuf:"bytes,2,opt,name=generated_text,json=generatedText,proto3" json:"generated_text,omitempty"`
	LatencyMs        float64                `protobuf:"fixed64,3,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"` // wall-clock request latency
	TtftMs           float64                `protobuf:"fixed64,4,opt,name=ttft_ms,json=ttftMs,proto3" json:"ttft_ms,omitempty"`          // time-to-first-token (streaming)
	TokensPerSec     float64                `protobuf:"fixed64,5,opt,name=tokens_per_sec,json=tokensPerSec,proto3" json:"tokens_per_sec,omitempty"`
	BleuScore        float64                `protobuf:"fixed64,6,opt,name=bleu_score,json=bleuScore,proto3" json:"bleu_score,omitempty"`                        // 0–1; 0 if no reference provided
	RougeL           float64                `protobuf:"fixed64,7,opt,name=rouge_l,json=rougeL,proto3" json:"rouge_l,omitempty"`                                 // ROUGE-L F1; 0 if no reference provided
	EstimatedCostUsd float64                `protobuf:"fixed64,8,opt,name=estimated_cost_usd,json=estimatedCostUsd,proto3" json:"estimated_cost_usd,omitempty"` // 0.0 for local models
	BackendType      string                 `protobuf:"bytes,9,opt,name=backend_type,json=backendType,proto3" json:"backend_type,omitempty"`                    // "gemma_hf" | "ollama" | "gemini"
	Quantization     string                 `protobuf:"bytes,10,opt,name=quantization,proto3" json:"quantization,omitempty"`                                    // "fp32" | "int4_nf4" | "q4_k_m" | "none"
	TokenCount       int32                  `protobuf:"varint,11,opt,name=token_count,json=tokenCount,proto3" json:"token_count,omitempty"`                     // number of generated tokens
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ModelMetrics) Reset() {
	*x = ModelMetrics{}
	mi := &file_llm_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelMetrics) ProtoMessage() {}

func (x *ModelMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_llm_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelMetrics.ProtoReflect.Descriptor instead.
func (*ModelMetrics) Descriptor() ([]byte, []int) {
	return file_llm_service_proto_rawDescGZIP(), []int{4}
}

func (x *ModelMetrics) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *ModelMetrics) GetGeneratedText() string {
	if x != nil {
		return x.GeneratedText
	}
	return ""
}

func (x *ModelMetrics) GetLatencyMs() float64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *ModelMetrics) GetTtftMs() float64 {
	if x != nil {
		return x.TtftMs
	}
	return 0
}

func (x *ModelMetrics) GetTokensPerSec() float64 {
	if x != nil {
		return x.TokensPerSec
	}
	return 0
}

func (x *ModelMetrics) GetBleuScore() float64 {
	if x != nil {
		return x.BleuScore
	}
	return 0
}

func (x *ModelMetrics) GetRougeL() float64 {
	if x != nil {
		return x.RougeL
	}
	return 0
}

func (x *ModelMetrics) GetEstimatedCostUsd() float64 {
	if x != nil {
		return x.EstimatedCostUsd
	}
	return 0
}

func (x *ModelMetrics) GetBackendType() string {
	if x != nil {
		return x.BackendType
	}
	return ""
}

func (x *ModelMetrics) GetQuantization() string {
	if x != nil {
		return x.Quantization
	}
	return ""
}

func (x *ModelMetrics) GetTokenCount() int32 {
	if x != nil {
		return x.TokenCount
	}
	return 0
}

type EvaluateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ModelMetrics        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	ReportPath    string                 `protobuf:"bytes,2,opt,name=report_path,json=reportPath,proto3" json:"report_path,omitempty"` // path to written JSON report
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateResponse) Reset() {
	*x = EvaluateResponse{}
	mi := &file_llm_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateResponse) ProtoMessage() {}

func (x *EvaluateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llm_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateResponse.ProtoReflect.Descriptor instead.
func (*EvaluateResponse) Descriptor() ([]byte, []int) {
	return file_llm_service_proto_rawDescGZIP(), []int{5}
}

func (x *EvaluateResponse) GetResults() []*ModelMetrics {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *EvaluateResponse) GetReportPath() string {
	if x != nil {
		return x.ReportPath
	}
	return ""
}

type BenchmarkRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Prompts               []string               `protobuf:"bytes,1,rep,name=prompts,proto3" json:"prompts,omitempty"`                                                             // prompts to run
	ModelIds              []string               `protobuf:"bytes,2,rep,name=model_ids,json=modelIds,proto3" json:"model_ids,omitempty"`                                           // models to compare
	RunsPerPrompt         int32                  `protobuf:"varint,3,opt,name=runs_per_prompt,json=runsPerPrompt,proto3" json:"runs_per_prompt,omitempty"`                         // repetitions for averaging (default 3)
	IncludeRestComparison bool                   `protobuf:"varint,4,opt,name=include_rest_comparison,json=includeRestComparison,proto3" json:"include_rest_comparison,omitempty"` // also hit Python /predict directly
	Temperature           float32                `protobuf:"fixed32,5,opt,name=temperature,proto3" json:"temperature,omitempty"`
	MaxNewTokens          int32                  `protobuf:"varint,6,opt,name=max_new_tokens,json=maxNewTokens,proto3" json:"max_new_tokens,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *BenchmarkRequest) Reset() {
	*x = BenchmarkRequest{}
	mi := &file_llm_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BenchmarkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BenchmarkRequest) ProtoMessage() {}

func (x *BenchmarkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llm_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BenchmarkRequest.ProtoReflect.Descriptor instead.
func (*BenchmarkRequest) Descriptor() ([]byte, []int) {
	return file_llm_service_proto_rawDescGZIP(), []int{6}
}

func (x *BenchmarkRequest) GetPrompts() []string {
	if x != nil {
		return x.Prompts
	}
	return nil
}

func (x *BenchmarkRequest) GetModelIds() []string {
	if x != nil {
		return x.ModelIds
	}
	return nil
}

func (x *BenchmarkRequest) GetRunsPerPrompt() int32 {
	if x != nil {
		return x.RunsPerPrompt
	}
	return 0
}

func (x *BenchmarkRequest) GetIncludeRestComparison() bool {
	if x != nil {
		return x.IncludeRestComparison
	}
	return false
}

func (x *BenchmarkRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *BenchmarkRequest) GetMaxNewTokens() int32 {
	if x != nil {
		return x.MaxNewTokens
	}
	return 0
}

// Aggregated stats across all prompts/runs for one model
type AggregatedMetrics struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ModelId          string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	AvgLatencyMs     float64                `protobuf:"fixed64,2,opt,name=avg_latency_ms,json=avgLatencyMs,proto3" json:"avg_latency_ms,omitempty"`
	P50LatencyMs     float64                `protobuf:"fixed64,3,opt,name=p50_latency_ms,json=p50LatencyMs,proto3" json:"p50_latency_ms,omitempty"`
	P95LatencyMs     float64                `protobuf:"fixed64,4,opt,name=p95_latency_ms,json=p95LatencyMs,proto3" json:"p95_latency_ms,omitempty"`
	P99LatencyMs     float64                `protobuf:"fixed64,5,opt,name=p99_latency_ms,json=p99LatencyMs,proto3" json:"p99_latency_ms,omitempty"`
	AvgTokensPerSec  float64                `protobuf:"fixed64,6,opt,name=avg_tokens_per_sec,json=avgTokensPerSec,proto3" json:"avg_tokens_per_sec,omitempty"`
	AvgBleu          float64                `protobuf:"fixed64,7,opt,name=avg_bleu,json=avgBleu,proto3" json:"avg_bleu,omitempty"`
	AvgRougeL        float64                `protobuf:"fixed64,8,opt,name=avg_rouge_l,json=avgRougeL,proto3" json:"avg_rouge_l,omitempty"`
	EstimatedCostUsd float64                `protobuf:"fixed64,9,opt,name=estimated_cost_usd,json=estimatedCostUsd,proto3" json:"estimated_cost_usd,omitempty"` // total across all runs
	BackendType      string                 `protobuf:"bytes,10,opt,name=backend_type,json=backendType,proto3" json:"backend_type,omitempty"`
	Quantization     string                 `protobuf:"bytes,11,opt,name=quantization,proto3" json:"quantization,omitempty"`
	TotalRuns        int32                  `protobuf:"varint,12,opt,name=total_runs,json=totalRuns,proto3" json:"total_runs,omitempty"`
	// REST comparison fields (populated when include_rest_comparison=true)
	RestAvgLatencyMs  float64 `protobuf:"fixed64,13,opt,name=rest_avg_latency_ms,json=restAvgLatencyMs,proto3" json:"rest_avg_latency_ms,omitempty"`
	GrpcVsRestDeltaMs float64 `protobuf:"fixed64,14,opt,name=grpc_vs_rest_delta_ms,json=grpcVsRestDeltaMs,proto3" json:"grpc_vs_rest_delta_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AggregatedMetrics) Reset() {
	*x = AggregatedMetrics{}
	mi := &file_llm_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregatedMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregatedMetrics) ProtoMessage() {}

func (x *AggregatedMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_llm_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregatedMetrics.ProtoReflect.Descriptor instead.
func (*AggregatedMetrics) Descriptor() ([]byte, []int) {
	return file_llm_service_proto_rawDescGZIP(), []int{7}
}

func (x *AggregatedMetrics) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *AggregatedMetrics) GetAvgLatencyMs() float64 {
	if x != nil {
		return x.AvgLatencyMs
	}
	return 0
}

func (x *AggregatedMetrics) GetP50LatencyMs() float64 {
	if x != nil {
		return x.P50LatencyMs
	}
	return 0
}

func (x *AggregatedMetrics) GetP95LatencyMs() float64 {
	if x != nil {
		return x.P95LatencyMs
	}
	return 0
}

func (x *AggregatedMetrics) GetP99LatencyMs() float64 {
	if x != nil {
		return x.P99LatencyMs
	}
	return 0
}

func (x *AggregatedMetrics) GetAvgTokensPerSec() float64 {
	if x != nil {
		return x.AvgTokensPerSec
	}
	return 0
}

func (x *AggregatedMetrics) GetAvgBleu() float64 {
	if x != nil {
		return x.AvgBleu
	}
	return 0
}

func (x *AggregatedMetrics) GetAvgRougeL() float64 {
	if x != nil {
		return x.AvgRougeL
	}
	return 0
}

func (x *AggregatedMetrics) GetEstimatedCostUsd() float64 {
	if x != nil {
		return x.EstimatedCostUsd
	}
	return 0
}

func (x *AggregatedMetrics) GetBackendType() string {
	if x != nil {
		return x.BackendType
	}
	return ""
}

func (x *AggregatedMetrics) GetQuantization() string {
	if x != nil {
		return x.Quantization
	}
	return ""
}

func (x *AggregatedMetrics) GetTotalRuns() int32 {
	if x != nil {
		return x.TotalRuns
	}
	return 0
}

func (x *AggregatedMetrics) GetRestAvgLatencyMs() float64 {
	if x != nil {
		return x.RestAvgLatencyMs
	}
	return 0
}

func (x *AggregatedMetrics) GetGrpcVsRestDeltaMs() float64 {
	if x != nil {
		return x.GrpcVsRestDeltaMs
	}
	return 0
}

type BenchmarkResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Aggregated     []*AggregatedMetrics   `protobuf:"bytes,1,rep,name=aggregated,proto3" json:"aggregated,omitempty"`
	JsonReportPath string                 `protobuf:"bytes,2,opt,name=json_report_path,json=jsonReportPath,proto3" json:"json_report_path,omitempty"`
	Summary        string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"` // human-readable summary table
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BenchmarkResponse) Reset() {
	*x = BenchmarkResponse{}
	mi := &file_llm_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BenchmarkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BenchmarkResponse) ProtoMessage() {}

func (x *BenchmarkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llm_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BenchmarkResponse.ProtoReflect.Descriptor instead.
func (*BenchmarkResponse) Descriptor() ([]byte, []int) {
	return file_llm_service_proto_rawDescGZIP(), []int{8}
}

func (x *BenchmarkResponse) GetAggregated() []*AggregatedMetrics {
	if x != nil {
		return x.Aggregated
	}
	return nil
}

func (x *BenchmarkResponse) GetJsonReportPath() string {
	if x != nil {
		return x.JsonReportPath
	}
	return ""
}

func (x *BenchmarkResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

var File_llm_service_proto protoreflect.FileDescriptor

const file_llm_service_proto_rawDesc = "" +
	"\n" +
	"\x11llm_service.proto\x12\vllm_service\"\x8c\x01\n" +
	"\x0fGenerateRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\x12 \n" +
	"\vtemperature\x18\x03 \x01(\x02R\vtemperature\x12$\n" +
	"\x0emax_new_tokens\x18\x04 \x01(\x05R\fmaxNewTokens\"9\n" +
	"\x10GenerateResponse\x12%\n" +
	"\x0egenerated_text\x18\x01 \x01(\tR\rgeneratedText\"O\n" +
	"\x16StreamGenerateResponse\x12!\n" +
	"\fpartial_text\x18\x01 \x01(\tR\vpartialText\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04done\"\xb9\x01\n" +
	"\x0fEvaluateRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12)\n" +
	"\x10reference_answer\x18\x02 \x01(\tR\x0freferenceAnswer\x12\x1b\n" +
	"\tmodel_ids\x18\x03 \x03(\tR\bmodelIds\x12 \n" +
	"\vtemperature\x18\x04 \x01(\x02R\vtemperature\x12$\n" +
	"\x0emax_new_tokens\x18\x05 \x01(\x05R\fmaxNewTokens\"\xfc\x02\n" +
	"\fModelMetrics\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12%\n" +
	"\x0egenerated_text\x18\x02 \x01(\tR\rgeneratedText\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x03 \x01(\x01R\tlatencyMs\x12\x17\n" +
	"\attft_ms\x18\x04 \x01(\x01R\x06ttftMs\x12$\n" +
	"\x0etokens_per_sec\x18\x05 \x01(\x01R\ftokensPerSec\x12\x1d\n" +
	"\n" +
	"bleu_score\x18\x06 \x01(\x01R\tbleuScore\x12\x17\n" +
	"\arouge_l\x18\a \x01(\x01R\x06rougeL\x12,\n" +
	"\x12estimated_cost_usd\x18\b \x01(\x01R\x10estimatedCostUsd\x12!\n" +
	"\fbackend_type\x18\t \x01(\tR\vbackendType\x12\"\n" +
	"\fquantization\x18\n" +
	" \x01(\tR\fquantization\x12\x1f\n" +
	"\vtoken_count\x18\v \x01(\x05R\n" +
	"tokenCount\"h\n" +
	"\x10EvaluateResponse\x123\n" +
	"\aresults\x18\x01 \x03(\v2\x19.llm_service.ModelMetricsR\aresults\x12\x1f\n" +
	"\vreport_path\x18\x02 \x01(\tR\n" +
	"reportPath\"\xf1\x01\n" +
	"\x10BenchmarkRequest\x12\x18\n" +
	"\aprompts\x18\x01 \x03(\tR\aprompts\x12\x1b\n" +
	"\tmodel_ids\x18\x02 \x03(\tR\bmodelIds\x12&\n" +
	"\x0fruns_per_prompt\x18\x03 \x01(\x05R\rrunsPerPrompt\x126\n" +
	"\x17include_rest_comparison\x18\x04 \x01(\bR\x15includeRestComparison\x12 \n" +
	"\vtemperature\x18\x05 \x01(\x02R\vtemperature\x12$\n" +
	"\x0emax_new_tokens\x18\x06 \x01(\x05R\fmaxNewTokens\"\xa3\x04\n" +
	"\x11AggregatedMetrics\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12$\n" +
	"\x0eavg_latency_ms\x18\x02 \x01(\x01R\favgLatencyMs\x12$\n" +
	"\x0ep50_latency_ms\x18\x03 \x01(\x01R\fp50LatencyMs\x12$\n" +
	"\x0ep95_latency_ms\x18\x04 \x01(\x01R\fp95LatencyMs\x12$\n" +
	"\x0ep99_latency_ms\x18\x05 \x01(\x01R\fp99LatencyMs\x12+\n" +
	"\x12avg_tokens_per_sec\x18\x06 \x01(\x01R\x0favgTokensPerSec\x12\x19\n" +
	"\bavg_bleu\x18\a \x01(\x01R\aavgBleu\x12\x1e\n" +
	"\vavg_rouge_l\x18\b \x01(\x01R\tavgRougeL\x12,\n" +
	"\x12estimated_cost_usd\x18\t \x01(\x01R\x10estimatedCostUsd\x12!\n" +
	"\fbackend_type\x18\n" +
	" \x01(\tR\vbackendType\x12\"\n" +
	"\fquantization\x18\v \x01(\tR\fquantization\x12\x1d\n" +
	"\n" +
	"total_runs\x18\f \x01(\x05R\ttotalRuns\x12-\n" +
	"\x13rest_avg_latency_ms\x18\r \x01(\x01R\x10restAvgLatencyMs\x120\n" +
	"\x15grpc_vs_rest_delta_ms\x18\x0e \x01(\x01R\x11grpcVsRestDeltaMs\"\x97\x01\n" +
	"\x11BenchmarkResponse\x12>\n" +
	"\n" +
	"aggregated\x18\x01 \x03(\v2\x1e.llm_service.AggregatedMetricsR\n" +
	"aggregated\x12(\n" +
	"\x10json_report_path\x18\x02 \x01(\tR\x0ejsonReportPath\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary2\xd9\x02\n" +
	"\n" +
	"LLMService\x12K\n" +
	"\fGenerateText\x12\x1c.llm_service.GenerateRequest\x1a\x1d.llm_service.GenerateResponse\x12Y\n" +
	"\x12StreamGenerateText\x12\x1c.llm_service.GenerateRequest\x1a#.llm_service.StreamGenerateResponse0\x01\x12Q\n" +
	"\x12EvaluateGeneration\x12\x1c.llm_service.EvaluateRequest\x1a\x1d.llm_service.EvaluateResponse\x12P\n" +
	"\x0fBenchmarkModels\x12\x1d.llm_service.BenchmarkRequest\x1a\x1e.llm_service.BenchmarkResponseB\bZ\x06.;mainb\x06proto3"

var (
	file_llm_service_proto_rawDescOnce sync.Once
	file_llm_service_proto_rawDescData []byte
)

func file_llm_service_proto_rawDescGZIP() []byte {
	file_llm_service_proto_rawDescOnce.Do(func() {
		file_llm_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_llm_service_proto_rawDesc), len(file_llm_service_proto_rawDesc)))
	})
	return file_llm_service_proto_rawDescData
}

var file_llm_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_llm_service_proto_goTypes = []any{
	(*GenerateRequest)(nil),        // 0: llm_service.GenerateRequest
	(*GenerateResponse)(nil),       // 1: llm_service.GenerateResponse
	(*StreamGenerateResponse)(nil), // 2: llm_service.StreamGenerateResponse
	(*EvaluateRequest)(nil),        // 3: llm_service.EvaluateRequest
	(*ModelMetrics)(nil),           // 4: llm_service.ModelMetrics
	(*EvaluateResponse)(nil),       // 5: llm_service.EvaluateResponse
	(*BenchmarkRequest)(nil),       // 6: llm_service.BenchmarkRequest
	(*AggregatedMetrics)(nil),      // 7: llm_service.AggregatedMetrics
	(*BenchmarkResponse)(nil),      // 8: llm_service.BenchmarkResponse
}
var file_llm_service_proto_depIdxs = []int32{
	4, // 0: llm_service.EvaluateResponse.results:type_name -> llm_service.ModelMetrics
	7, // 1: llm_service.BenchmarkResponse.aggregated:type_name -> llm_service.AggregatedMetrics
	0, // 2: llm_service.LLMService.GenerateText:input_type -> llm_service.GenerateRequest
	0, // 3: llm_service.LLMService.StreamGenerateText:input_type -> llm_service.GenerateRequest
	3, // 4: llm_service.LLMService.EvaluateGeneration:input_type -> llm_service.EvaluateRequest
	6, // 5: llm_service.LLMService.BenchmarkModels:input_type -> llm_service.BenchmarkRequest
	1, // 6: llm_service.LLMService.GenerateText:output_type -> llm_service.GenerateResponse
	2, // 7: llm_service.LLMService.StreamGenerateText:output_type -> llm_service.StreamGenerateResponse
	5, // 8: llm_service.LLMService.EvaluateGeneration:output_type -> llm_service.EvaluateResponse
	8, // 9: llm_service.LLMService.BenchmarkModels:output_type -> llm_service.BenchmarkResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_llm_service_proto_init() }
func file_llm_service_proto_init() {
	if File_llm_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_llm_service_proto_rawDesc), len(file_llm_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_llm_service_proto_goTypes,
		DependencyIndexes: file_llm_service_proto_depIdxs,
		MessageInfos:      file_llm_service_proto_msgTypes,
	}.Build()
	File_llm_service_proto = out.File
	file_llm_service_proto_goTypes = nil
	file_llm_service_proto_depIdxs = nil
}
